[package]
name = "n64disasm"
version = "0.1.0"
authors = ["tehz <tehzz@users.noreply.github.com>"]
edition = "2018"

[dependencies]
structopt = "0.3.3"
err-derive = "0.2.1"
serde = {version = "1.0.*", features = ["derive"]}
serde_yaml = "0.8.*"
